spring:
  application:
    name: discord-sports-bot
discord:
  api-token: token-goes-here
  #todo: use env var for this and then regenerate token once I have something more secure
api:
  api-football: token-goes-here